### PR TITLE
Update readme example and draft of constant kernel

### PR DESCRIPTION
**Pull request by edejong-caltech**
One small fix to README example to run properly, plus attempt to implement a constant collision kernel. This first attempt uses the `sum_pairs` function as a workaround to size the output array properly; ideally the constant kernel would be more efficient and would avoid this workaround. Tutorials on specifying one's own kernel would be helpful: for example, how to create a polynomial kernel of the form `f(r, r')` rather than `f(r+r')`.

### CODE REVIEW

**Comment by claresinger** [comment]
https://github.com/claresinger/PySDM/tree/fix_readme updates the markdown text of the README.md file

**Comment by slayoo** [comment]
Thank you!
The README update is now already in master branch.
Stay tuned for more feedback on the kernels.

**Comment by claresinger** [comment]
Thanks @slayoo! One note, I think in the README the `get_particles()` method is now called `build()`. So in the description of what the usage example does that should be updated.

This >>
```Finally, the ``get_particles()`` method is used to obtain an instance
  of ``Core`` which can then be used to control time-stepping and
  access simulation state.```

**Comment by piotrbartman** [comment]
Constant kernel `__call__` method can be simply implemented as:
```Python
def __call__(self, output, is_first_in_pair):
    output.product(is_first_in_pair, self.kernel_const)
```

To create a polynomial kernel look [at this branch](https://github.com/piotrbartman/PySDM/tree/polynomial), but it hasn't been tested yet.
With it, kernel such as `f(R, r) = 2R^3 + R^0.5 - r^2`,, where `R>=r` can be implemented as something like that:
```Python
def __call__(self, output, is_first_in_pair):
    self.tmp.sort_pair(self.core.state['radius'], is_first_in_pair) #pair in order (R, r) to temporary memory self.tmp: see gravitational.py
    output.polynomial_pair(self.tmp, is_first_in_pair, coef_0=(2, 1), coef_1=(-1,), pow_0=(3, 0.5), pow_1=(2))
```

**Comment by slayoo** [comment]
Thanks @claresinger for reporting the README issues. From now on (https://github.com/atmos-cloud-sim-uj/PySDM/commit/c25fdde81fedd1da5d2c038ab242b039c3bcd196#diff-354f30a63fb0907d4ad57269548329e3) all Python code from README is executed on Travis - should help to maintain it.

**Comment by claresinger** [comment]
@edejong-caltech Now that the readme has been updated and we have answers for how to implement the generic polynomial kernels, this PR can probably be deleted, yes?

**Comment by slayoo** [comment]
Still, I've added a "backends and kernels readme with examples" issue: https://github.com/atmos-cloud-sim-uj/PySDM/issues/200

**Pull request closed without merging**
