### PR TITLE
Add Lv and k from Lowe et al 2019

### PR DESCRIPTION
**Pull request by claresinger**

### CODE REVIEW

**Comment by claresinger** [comment]
See issue #760 for info

**Comment by slayoo** [comment]
here, let's add some basic unit tests for the new L(T) and K(T) at least to ensure that the new code is executed at all on CI, and perhaps also just check if the values are not too far from previously used formulations

**Comment by claresinger** [comment]
I'll add a test like exists for saturation vapor pressure with the option to plot the different formulations.

**Comment by claresinger** [comment]
Test 1:
latent_heats

Test 2:
thermal_conductivities

**Pull request merged**
