### PR TITLE
add thurstRTC moments

### PR DESCRIPTION
**Pull request by tehAgitto**
Regarding #246, we want to get rid of the kludge 
@kyetuur

### CODE REVIEW

**Comment by slayoo** [comment]
Big thanks!

The failures seem to all be caused by:
```
E       atomicAdd((unsigned long long int*)&moment_0[cell_id[i]], (unsigned long long int)n[i]);
E                              ^
E   SyntaxError: invalid syntax
```

**Comment by piotrbartman** [comment]
It is a problem with `FakeThrust`, it doesn't recognize `atomicAdd`. I wonder how to fixed it, but I don't have any idea.

**Comment by slayoo** [comment]
Here are some measurements done before merging using the Shima_et_al_2009 example run on Colab:

n_plot=8
adaptive_dt=off
CPU:
  - log_2(n_sd)=12 -> wall time: 1.34 s
  - log_2(n_sd)=15 -> wall time: 6.38 s
  - log_2(n_sd)=18 -> wall time: 54.5 s
GPU (old):
  - log_2(n_sd)=12 -> wall time: 6.03 s
  - log_2(n_sd)=15 -> wall time: 42.5 s
  - log_2(n_sd)=18 -> wall time: 373 s

**Comment by slayoo** [comment]
GPU (new):
- log_2(n_sd)=12 -> wall time: 5.36 s
- log_2(n_sd)=15 -> wall time: 40.6 s
- log_2(n_sd)=18 -> wall time: 355 s

**Comment by slayoo** [comment]
On the other hand, changing the number of steps to 8, one can see the GPU speedup:
- GPU: 1.7 s
- CPU: 4.9 s

**Pull request merged**
