### PR TITLE
surface tension tests

### LINKED ISSUE #880: add a test asserting if parcel model results for f_org=0 are same across all surface tension representations

### PR DESCRIPTION
**Pull request by claresinger**
will close #880

### CODE REVIEW

**Comment by slayoo** [comment]
thank you, Clare!

**Comment by claresinger** [comment]
Plots from new tests :)
test_zero_forg
test_surface_tension_Forg0
test_surface_tension_Forg1

**Comment by slayoo** [comment]
closing and reopening to re-trigger builds on current main branch

**Comment by claresinger** [comment]
@edejong-caltech I'm going to need you to update your branch of PySDM-examples from upstream in order for this PR to pass tests. It would be nice next time to merge any changes needed for smoke_tests into PySDM-examples main before you merge PySDM PRs in the future to avoid this problem.

**Comment by slayoo** [comment]
Merging!
Thank you, Clare!

**Pull request merged**
