### PR TITLE
BDF condensation in pyrcel smoke tests + work in progress on more test coverage for condensation

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by claresinger** [comment]
This is great! Thank you @slayoo 🎉

**Comment by claresinger** [comment]
@slayoo What is this PR waiting on? Can I help get it merged? It would be good to have this in for v2 if we are planning to show a pyrcel figure :)

**Comment by slayoo** [comment]
Thanks, Clare for the ping.
Just fixed conflicts, let's see what the CI runs will report back

**Comment by claresinger** [comment]
> Thanks, Clare for the ping.
> Just fixed conflicts, let's see what the CI runs will report back

Seems like there is some issue installing `PySDM-examples`

**Pull request merged**
